// Static profession list for the booking form. There is no free, keyless public API that
// returns a clean list of professions (ESCO / O*NET / LinkedIn all need registration and
// return thousands of granular job titles), so a curated list is used: it works offline,
// can't fail at page load, and is easy to edit. "Other" (last) lets the customer type their own.
const PROFESSIONS = [
  "Accountant / Chartered Accountant",
  "Actor / Performer",
  "Architect",
  "Artist / Designer (Creative)",
  "Banker / Finance Professional",
  "Business Analyst",
  "Business Owner / Entrepreneur",
  "Chef / Hospitality Professional",
  "Civil Servant / Government Employee",
  "Consultant",
  "Content Creator / Influencer",
  "Counsellor / Therapist",
  "Customer Support Executive",
  "Data Scientist / Analyst",
  "Defence / Armed Forces",
  "Dentist",
  "Doctor / Physician",
  "Driver / Transport Professional",
  "Electrician / Technician",
  "Engineer (Civil / Mechanical / Electrical)",
  "Farmer / Agriculture",
  "Fashion Designer",
  "Fitness Trainer / Coach",
  "Freelancer",
  "Graphic / UI-UX Designer",
  "HR Professional",
  "Homemaker",
  "Insurance Professional",
  "Interior Designer",
  "Journalist / Media Professional",
  "Judge / Legal Professional",
  "Lawyer / Advocate",
  "Manager / Executive",
  "Marketing / Sales Professional",
  "Nurse / Healthcare Worker",
  "Pharmacist",
  "Photographer / Videographer",
  "Pilot / Aviation Professional",
  "Police / Security Services",
  "Professor / Lecturer",
  "Project / Product Manager",
  "Real Estate Professional",
  "Researcher / Scientist",
  "Retired",
  "Software Engineer / IT Professional",
  "Student",
  "Teacher / Educator",
  "Writer / Author / Editor",
  "Unemployed / Between Jobs",
];
const OTHER_PROFESSION = "Other";
